version: "3.4"
services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    command: "bash start.sh"
    environment:
      HOST: ${HOST}
    ports:
      - "${SERVER_PORT}:5000"
